<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-I44L1MS" failures="1" tests="3" name="Test" time="13.597" errors="0" timestamp="2025-07-02T05:08:28 IST">
  <testcase classname="testcases.RegistrationTestCases" name="verifyRegistrationWithValidData" time="3.963"/>
  <testcase classname="testcases.LoginTestCases" name="verifyLoginwithValidData" time="1.838">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [https://naveenautomationlabs.com/opencart/index.php?route=account/account] but found [https://naveenautomationlabs.com/opencart/index.php?route=account/login]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://naveenautomationlabs.com/opencart/index.php?route=account/account] but found [https://naveenautomationlabs.com/opencart/index.php?route=account/login]
at testcases.LoginTestCases.verifyLoginwithValidData(LoginTestCases.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- verifyLoginwithValidData -->
  <testcase classname="testcases.AddToCartTestCase" name="verifyAddToCartwithvaliddata" time="0.793"/>
  <testcase classname="testcases.RegistrationTestCases" name="verifyRegistrationWithBlankData" time="0.0">
    <ignored/>
  </testcase> <!-- verifyRegistrationWithBlankData -->
</testsuite> <!-- Test -->
